name: BitlanBuild
version: '${project.version}'
main: dev.stjernholm.bitlanbuild.BitlanBuild
api-version: '1.21'
depend:
  - PlotSquared
  - WorldGuard
commands:
  plot:
  theme:
    permission: bitlan.superop
  vote:
    permission: bitlan.op
  result:
    permission: bitlan.superop